services: ## all your services need to be down below services as if you want to run multi container simultaneously
  postgres: ## this will be your service name
    image: postgres ## this is image which will run in container
    environment:  ## in this section you will write all the things necessary when run a container
      - POSTGRES_PASSWORD=postgrespwd
    ports: ## the right is the port which image is use in container and left is the container will expose to outside world
      - 5432:5432
    volumes: ## this tag is used when you want acquire space from the os
      - pgdata:/var/lib/postgresql/data

volumes: ## Specify all volumes here used in your multi containers app
  pgdata: